#!/bin/env zsh

dir=$(pwd)

cd "${dir}/sy-progressive-plugin"
rm -rf dev dist .eslintcache package.zip node_modules
pnpm i

cd "${dir}/sy-tomato-plugin"
rm -rf dev dist .eslintcache package.zip node_modules
pnpm i

