#!/bin/env zsh
set -xe

cd ${0:a:h}

if [[ -z "${1}" ]]; then
    exit
fi

projDir=${0:a:h}/sy-${1}-plugin
projName=${projDir:t}

targetDir="${SYPLUGINDIR}/${projName}"

cd ${projDir}
pnpm build

rm -rf ${targetDir}
mkdir -p ${targetDir}
cp -r ${projDir}/dist/* ${targetDir}


