#!/bin/env zsh
set -xe

cd ${0:a:h}

if [[ -z "${1}" ]]; then
    exit
fi

./deploy ${1}

projDir=${0:a:h}/sy-${1}-plugin
projName="${projDir:t}"
deployDir="${projDir:h}/deploy-repos/${projName}"
cd ${projDir}

current_version=$(jq -r '.version' plugin.json)
IFS='.' read -r major minor patch <<< "$current_version"
((patch++))
new_version="${major}.${minor}.${patch}"
plugins_new_version="${new_version}-${projName}"
sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" plugin.json
git add -A
git commit -m "auto"
git tag v${plugins_new_version}
git push origin v${plugins_new_version}
git push origin main
git push -f gitee v${plugins_new_version}
git push -f gitee main

rsync -ru \
    .github \
    assets \
    *.md \
    LICENSE \
    *.png \
    *.json \
    "${deployDir}/"

cd ${deployDir}
git add -A
git commit -m "auto"
git tag v${new_version}
git push -f origin v${new_version}
git push -f origin main

cd ${projDir}
