#!/bin/env zsh
set -xe

cd ${0:a:h}

if [[ -z "${1}" ]]; then
    exit
fi

projDir=${0:a:h}/sy-${1}-plugin
projName=${projDir:t}

rm -rf "${SYPLUGINDIR}/${projName}"
cd ${SYPLUGINDIR}
ln -s "${projDir}/dev" "${projName}"

cd ${projDir}
pnpm run lint
pnpm run dev


