#!/bin/env zsh

projDir=${0:a:h}
projName=${0:a:h:t}
cd ${projDir}

current_version=$(jq -r '.version' plugin.json)
IFS='.' read -r major minor patch <<< "$current_version"
((patch++))
new_version="${major}.${minor}.${patch}"
plugins_new_version="${new_version}-${projName}"
sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" plugin.json
git add -A
git commit -m "auto"
latest_tag=$(git describe --tags --abbrev=0)
git tag v${plugins_new_version}
git push origin v${plugins_new_version}
git push gitee v${plugins_new_version}
git push origin
git push gitee

rsync -ru \
    .github \
    assets \
    *.md \
    LICENSE \
    *.png \
    *.json \
    ../deploy-repos/sy-progressive-plugin/

