#!/bin/env zsh


projDir="${0:a:h}"
deployDir="${projDir:h}/deploy-repos/sy-progressive-plugin"
projName="${projDir:t}"
cd ${projDir}

current_version=$(jq -r '.version' plugin.json)
IFS='.' read -r major minor patch <<< "$current_version"
((patch++))
new_version="${major}.${minor}.${patch}"
plugins_new_version="${new_version}-${projName}"
sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" plugin.json
git add -A
git commit -m "auto"
git tag v${plugins_new_version}
git push origin v${plugins_new_version}
git push gitee v${plugins_new_version}
git push origin
git push gitee

rsync -ru \
    .github \
    assets \
    *.md \
    LICENSE \
    *.png \
    *.json \
    "${deployDir}/"

cd ${deployDir}
git add -A
git commit -m "auto"
git tag v${new_version}
git push -f origin v${new_version}
git push -f origin

cd ${projDir}
